name: Build on Linux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-2.0-0 \
            libsdl2-mixer-2.0-0 \
            libtag1v5 \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libtag1-dev \
            cmake \
            build-essential \
            pkg-config


      # Configure and build the project
      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build the project
        run: |
          cd build
          make
